version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    env_file:
      - ./envs/web
    volumes:
      - ./:/app/:z
    ports:
      - "{{cookiecutter.port}}:{{cookiecutter.port}}"

  db:
    image: postgres:13
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./envs/web
    ports:
      - "5432"

  requirements:
    image: python:3.8-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z

  tests-{{cookiecutter.package_name}}:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    image: tests_{{cookiecutter.package_name}}
    env_file:
      - ./envs/tests
    profiles:
      - testing
    depends_on:
      - {{cookiecutter.package_name}}-test-db

  {{cookiecutter.package_name}}-test-db:
    image: postgres:13
    container_name: {{cookiecutter.package_name}}_test_postgres
    env_file:
      - ./envs/tests
    expose:
      - "5432"